name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit Scan
      run: |
        bandit -r . --severity-level high

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-report.txt